2019-08-01 10:14:00,015  __init__/__init__.py:73  _________visit start_________2019-08-01 10:14:00
2019-08-01 10:14:03,295  __init__/__init__.py:73  ip不可用：http://58.22.222.88:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04372490>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-01 10:14:06,326  __init__/__init__.py:73  ip不可用：http://58.22.213.107:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x04372910>, 'Connection to 58.22.213.107 timed out. (connect timeout=2)'))
2019-08-01 10:14:09,343  __init__/__init__.py:73  ip不可用：http://203.110.164.139:52144HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x04372D10>, 'Connection to 203.110.164.139 timed out. (connect timeout=2)'))
2019-08-01 10:14:11,483  __init__/__init__.py:73  ip不可用：http://117.90.1.198:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05050170>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-01 10:14:14,499  __init__/__init__.py:73  ip不可用：http://117.90.2.35:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x04372FF0>, 'Connection to 117.90.2.35 timed out. (connect timeout=2)'))
2019-08-01 10:14:16,608  __init__/__init__.py:73  ip不可用：http://121.232.148.191:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04372CF0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-01 10:14:19,640  __init__/__init__.py:73  ip不可用：http://175.44.148.100:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x043728F0>, 'Connection to 175.44.148.100 timed out. (connect timeout=2)'))
2019-08-01 10:14:22,670  __init__/__init__.py:73  ip不可用：http://180.118.135.47:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x050505B0>, 'Connection to 180.118.135.47 timed out. (connect timeout=2)'))
2019-08-01 10:14:24,796  __init__/__init__.py:73  ip不可用：http://117.90.1.131:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05050050>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-01 10:14:27,814  __init__/__init__.py:73  ip不可用：http://14.29.232.142:8082HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x05050B70>, 'Connection to 14.29.232.142 timed out. (connect timeout=2)'))
2019-08-01 10:14:29,876  __init__/__init__.py:73  ip不可用：http://36.111.146.161:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05050E10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-01 10:14:31,985  __init__/__init__.py:73  ip不可用：http://117.90.1.201:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05050C50>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-01 10:14:35,017  __init__/__init__.py:73  ip不可用：http://60.188.38.186:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x05050830>, 'Connection to 60.188.38.186 timed out. (connect timeout=2)'))
2019-08-01 10:14:36,282  __init__/__init__.py:73  ip不可用：http://115.28.148.192:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-08-01 10:14:38,454  __init__/__init__.py:73  ip不可用：http://121.232.194.91:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x050507F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-01 10:14:39,469  __init__/__init__.py:73  _________visit end_________
2019-08-01 10:14:39
2019-08-01 10:15:00,017  __init__/__init__.py:73  _________visit start_________2019-08-01 10:15:00
2019-08-01 10:15:03,220  __init__/__init__.py:73  ip不可用：http://58.22.222.88:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04372450>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-01 10:15:06,250  __init__/__init__.py:73  ip不可用：http://58.22.213.107:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x04372C30>, 'Connection to 58.22.213.107 timed out. (connect timeout=2)'))
2019-08-01 10:15:09,267  __init__/__init__.py:73  ip不可用：http://203.110.164.139:52144HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0435D610>, 'Connection to 203.110.164.139 timed out. (connect timeout=2)'))
2019-08-01 10:15:11,376  __init__/__init__.py:73  ip不可用：http://117.90.1.198:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x050614B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-01 10:15:14,392  __init__/__init__.py:73  ip不可用：http://117.90.2.35:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x04372E30>, 'Connection to 117.90.2.35 timed out. (connect timeout=2)'))
2019-08-01 10:15:16,533  __init__/__init__.py:73  ip不可用：http://121.232.148.191:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x04372330>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-01 10:15:19,548  __init__/__init__.py:73  ip不可用：http://175.44.148.100:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0435D830>, 'Connection to 175.44.148.100 timed out. (connect timeout=2)'))
2019-08-01 10:15:22,578  __init__/__init__.py:73  ip不可用：http://180.118.135.47:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x05050170>, 'Connection to 180.118.135.47 timed out. (connect timeout=2)'))
2019-08-01 10:15:25,596  __init__/__init__.py:73  ip不可用：http://117.90.1.131:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x05050AD0>, 'Connection to 117.90.1.131 timed out. (connect timeout=2)'))
2019-08-01 10:15:27,189  __init__/__init__.py:73  ip不可用：http://14.29.232.142:8082HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-08-01 10:15:29,267  __init__/__init__.py:73  ip不可用：http://36.111.146.161:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x050613D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-01 10:15:31,375  __init__/__init__.py:73  ip不可用：http://117.90.1.201:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05050FB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-01 10:15:34,393  __init__/__init__.py:73  ip不可用：http://60.188.38.186:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x05050830>, 'Connection to 60.188.38.186 timed out. (connect timeout=2)'))
2019-08-01 10:15:35,565  __init__/__init__.py:73  ip不可用：http://115.28.148.192:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-08-01 10:15:37,752  __init__/__init__.py:73  ip不可用：http://121.232.194.91:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05050950>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-01 10:15:38,753  __init__/__init__.py:73  _________visit end_________
2019-08-01 10:15:38
2019-08-01 10:16:00,007  __init__/__init__.py:73  _________visit start_________2019-08-01 10:16:00
2019-08-01 10:16:03,272  __init__/__init__.py:73  ip不可用：http://58.22.222.88:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x043723F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-01 10:16:06,303  __init__/__init__.py:73  ip不可用：http://58.22.213.107:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x05061030>, 'Connection to 58.22.213.107 timed out. (connect timeout=2)'))
