2019-08-02 11:10:32,205  __init__/__init__.py:73  ip不可用：https://49.81.82.26:42594HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
2019-08-02 11:10:34,328  __init__/__init__.py:73  json解析错误>>：https://49.81.82.26:42594HTTPSConnectionPool(host='ditu.amap.com', port=443): Max retries exceeded with url: /detail/get/detail?id=B0FFIPJE9Z (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
2019-08-02 11:10:36,453  __init__/__init__.py:73  json解析错误>>：https://49.81.82.26:42594HTTPSConnectionPool(host='ditu.amap.com', port=443): Max retries exceeded with url: /detail/get/detail?id=B0FFF4VIBD (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
2019-08-02 11:10:38,573  __init__/__init__.py:73  json解析错误>>：https://49.81.82.26:42594HTTPSConnectionPool(host='map.baidu.com', port=443): Max retries exceeded with url: /?newmap=1&reqflag=pcmap&biz=1&from=webmap&da_par=direct&pcevaname=pc4.1&qt=s&da_src=searchBox.button&wd=%E8%B5%B5%E5%9B%9B%E9%A5%B8%E9%A5%B9%E9%9D%A2&c=2589&src=0&wd2=&pn=0&sug=0&l=10&b=(12356672.188326357,4809792.545941422;12556426.244393302,4970411.113472803)&from=webmap&biz_forward=%7B%22scaler%22:2,%22styles%22:%22pl%22%7D&sug_forward=&auth=KFE8H5I%40A9G04PDN00Ef%3D0MMK%40aCHd%3DWuxHLENxzzHxtDpnSCE%40%40By1uVt1GgvPUDZYOYIZuVt1cv3uVtGccZcuVtPWv3GuBtR9KxXwUvhgMZSguxzBEHLNRTVtcEWe1GD8zv7u%40ZPuVteuztexZFTHrwzDvqs2osGIRVOXI33LXFuyWWJL0IBggc1a&device_ratio=2&tn=B_NORMAL_MAP&nn=0&u_loc=12967743,4840033&ie=utf-8&t=1564712258807 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
2019-08-02 11:10:40,698  __init__/__init__.py:73  json解析错误>>：https://49.81.82.26:42594HTTPSConnectionPool(host='map.baidu.com', port=443): Max retries exceeded with url: /?newmap=1&reqflag=pcmap&biz=1&from=webmap&da_par=after_baidu&pcevaname=pc4.1&qt=s&da_src=searchBox.button&wd=%E6%B4%BB%E9%B1%BC%E5%86%9C%E5%AE%B6%E8%8F%9C&c=168&src=0&wd2=&pn=0&sug=0&l=19&b=(12524462.465,4915415;12524952.465,4915809)&from=webmap&biz_forward=%7B%22scaler%22:2,%22styles%22:%22pl%22%7D&sug_forward=&auth=F468SdW9ODYCQDfxcDa7KLFxbaxGBPX3uxHLENxxNHEtBnlQADZZzy1uVt1GgvPUDZYOYIZuVt1cv3uVtGccZcuVtPWv3GuztQZ3wWvUvhgMZSguxzBEHLNRTVtcEWe1GD8zv7u%40ZPuVtcvY1SGpuxztpFNEhjzgjyBKOHQBBODKximNNzCPyGllhIK&device_ratio=2&tn=B_NORMAL_MAP&nn=0&u_loc=12967743,4840033&ie=utf-8&t=1564711758575 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 403 Forbidden')))
2019-08-02 11:10:43,839  __init__/__init__.py:73  ip不可用：https://49.76.86.71:47551HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03C6FC70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-02 11:10:46,963  __init__/__init__.py:73  json解析错误>>：https://49.76.86.71:47551HTTPSConnectionPool(host='ditu.amap.com', port=443): Max retries exceeded with url: /detail/get/detail?id=B0FFIPJE9Z (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03ED30B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-02 11:10:50,103  __init__/__init__.py:73  json解析错误>>：https://49.76.86.71:47551HTTPSConnectionPool(host='ditu.amap.com', port=443): Max retries exceeded with url: /detail/get/detail?id=B0FFF4VIBD (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03ED34D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-02 11:10:53,215  __init__/__init__.py:73  json解析错误>>：https://49.76.86.71:47551HTTPSConnectionPool(host='map.baidu.com', port=443): Max retries exceeded with url: /?newmap=1&reqflag=pcmap&biz=1&from=webmap&da_par=direct&pcevaname=pc4.1&qt=s&da_src=searchBox.button&wd=%E8%B5%B5%E5%9B%9B%E9%A5%B8%E9%A5%B9%E9%9D%A2&c=2589&src=0&wd2=&pn=0&sug=0&l=10&b=(12356672.188326357,4809792.545941422;12556426.244393302,4970411.113472803)&from=webmap&biz_forward=%7B%22scaler%22:2,%22styles%22:%22pl%22%7D&sug_forward=&auth=KFE8H5I%40A9G04PDN00Ef%3D0MMK%40aCHd%3DWuxHLENxzzHxtDpnSCE%40%40By1uVt1GgvPUDZYOYIZuVt1cv3uVtGccZcuVtPWv3GuBtR9KxXwUvhgMZSguxzBEHLNRTVtcEWe1GD8zv7u%40ZPuVteuztexZFTHrwzDvqs2osGIRVOXI33LXFuyWWJL0IBggc1a&device_ratio=2&tn=B_NORMAL_MAP&nn=0&u_loc=12967743,4840033&ie=utf-8&t=1564712258807 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03ED3A10>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-02 11:10:56,370  __init__/__init__.py:73  json解析错误>>：https://49.76.86.71:47551HTTPSConnectionPool(host='map.baidu.com', port=443): Max retries exceeded with url: /?newmap=1&reqflag=pcmap&biz=1&from=webmap&da_par=after_baidu&pcevaname=pc4.1&qt=s&da_src=searchBox.button&wd=%E6%B4%BB%E9%B1%BC%E5%86%9C%E5%AE%B6%E8%8F%9C&c=168&src=0&wd2=&pn=0&sug=0&l=19&b=(12524462.465,4915415;12524952.465,4915809)&from=webmap&biz_forward=%7B%22scaler%22:2,%22styles%22:%22pl%22%7D&sug_forward=&auth=F468SdW9ODYCQDfxcDa7KLFxbaxGBPX3uxHLENxxNHEtBnlQADZZzy1uVt1GgvPUDZYOYIZuVt1cv3uVtGccZcuVtPWv3GuztQZ3wWvUvhgMZSguxzBEHLNRTVtcEWe1GD8zv7u%40ZPuVtcvY1SGpuxztpFNEhjzgjyBKOHQBBODKximNNzCPyGllhIK&device_ratio=2&tn=B_NORMAL_MAP&nn=0&u_loc=12967743,4840033&ie=utf-8&t=1564711758575 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03ED3E30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-02 11:11:01,635  __init__/__init__.py:73  json解析错误>>高德地图：https://116.209.117.252:27390'NoneType' object has no attribute 'get'
2019-08-02 11:11:08,416  __init__/__init__.py:73  json解析错误>>高德地图：https://116.209.117.252:27390'NoneType' object has no attribute 'get'
2019-08-02 11:11:20,073  __init__/__init__.py:73  json解析错误>>高德地图：https://116.209.117.252:27390'NoneType' object has no attribute 'get'
2019-08-02 11:11:22,495  __init__/__init__.py:73  json解析错误>>高德地图：https://116.209.117.252:27390'NoneType' object has no attribute 'get'
2019-08-02 11:11:34,416  __init__/__init__.py:73  json解析错误>>：https://116.209.117.252:27390HTTPSConnectionPool(host='map.baidu.com', port=443): Max retries exceeded with url: /?newmap=1&reqflag=pcmap&biz=1&from=webmap&da_par=after_baidu&pcevaname=pc4.1&qt=s&da_src=searchBox.button&wd=%E6%B4%BB%E9%B1%BC%E5%86%9C%E5%AE%B6%E8%8F%9C&c=168&src=0&wd2=&pn=0&sug=0&l=19&b=(12524462.465,4915415;12524952.465,4915809)&from=webmap&biz_forward=%7B%22scaler%22:2,%22styles%22:%22pl%22%7D&sug_forward=&auth=F468SdW9ODYCQDfxcDa7KLFxbaxGBPX3uxHLENxxNHEtBnlQADZZzy1uVt1GgvPUDZYOYIZuVt1cv3uVtGccZcuVtPWv3GuztQZ3wWvUvhgMZSguxzBEHLNRTVtcEWe1GD8zv7u%40ZPuVtcvY1SGpuxztpFNEhjzgjyBKOHQBBODKximNNzCPyGllhIK&device_ratio=2&tn=B_NORMAL_MAP&nn=0&u_loc=12967743,4840033&ie=utf-8&t=1564711758575 (Caused by ProxyError('Cannot connect to proxy.', timeout('_ssl.c:1039: The handshake operation timed out')))
2019-08-02 11:11:39,401  __init__/__init__.py:73  json解析错误>>高德地图：https://116.209.117.252:27390'NoneType' object has no attribute 'get'
2019-08-02 11:11:41,869  __init__/__init__.py:73  json解析错误>>高德地图：https://116.209.117.252:27390'NoneType' object has no attribute 'get'
2019-08-02 11:11:54,354  __init__/__init__.py:73  json解析错误>>高德地图：https://116.209.117.252:27390'NoneType' object has no attribute 'get'
2019-08-02 11:12:00,761  __init__/__init__.py:73  json解析错误>>高德地图：https://116.209.117.252:27390'NoneType' object has no attribute 'get'
2019-08-02 11:12:13,511  __init__/__init__.py:73  json解析错误>>高德地图：https://116.209.117.252:27390'NoneType' object has no attribute 'get'
2019-08-02 11:12:16,026  __init__/__init__.py:73  json解析错误>>高德地图：https://116.209.117.252:27390'NoneType' object has no attribute 'get'
2019-08-02 11:12:31,448  __init__/__init__.py:73  json解析错误>>：https://116.209.117.252:27390HTTPSConnectionPool(host='ditu.amap.com', port=443): Max retries exceeded with url: /detail/get/detail?id=B0FFIPJE9Z (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x03C6FEF0>, 'Connection to 116.209.117.252 timed out. (connect timeout=5)'))
2019-08-02 11:12:38,450  __init__/__init__.py:73  json解析错误>>：https://116.209.117.252:27390HTTPSConnectionPool(host='ditu.amap.com', port=443): Max retries exceeded with url: /detail/get/detail?id=B0FFF4VIBD (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x03C6FBD0>, 'Connection to 116.209.117.252 timed out. (connect timeout=5)'))
2019-08-02 11:12:45,469  __init__/__init__.py:73  json解析错误>>：https://116.209.117.252:27390HTTPSConnectionPool(host='map.baidu.com', port=443): Max retries exceeded with url: /?newmap=1&reqflag=pcmap&biz=1&from=webmap&da_par=direct&pcevaname=pc4.1&qt=s&da_src=searchBox.button&wd=%E8%B5%B5%E5%9B%9B%E9%A5%B8%E9%A5%B9%E9%9D%A2&c=2589&src=0&wd2=&pn=0&sug=0&l=10&b=(12356672.188326357,4809792.545941422;12556426.244393302,4970411.113472803)&from=webmap&biz_forward=%7B%22scaler%22:2,%22styles%22:%22pl%22%7D&sug_forward=&auth=KFE8H5I%40A9G04PDN00Ef%3D0MMK%40aCHd%3DWuxHLENxzzHxtDpnSCE%40%40By1uVt1GgvPUDZYOYIZuVt1cv3uVtGccZcuVtPWv3GuBtR9KxXwUvhgMZSguxzBEHLNRTVtcEWe1GD8zv7u%40ZPuVteuztexZFTHrwzDvqs2osGIRVOXI33LXFuyWWJL0IBggc1a&device_ratio=2&tn=B_NORMAL_MAP&nn=0&u_loc=12967743,4840033&ie=utf-8&t=1564712258807 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x03ED36D0>, 'Connection to 116.209.117.252 timed out. (connect timeout=5)'))
2019-08-02 11:12:52,495  __init__/__init__.py:73  json解析错误>>：https://116.209.117.252:27390HTTPSConnectionPool(host='map.baidu.com', port=443): Max retries exceeded with url: /?newmap=1&reqflag=pcmap&biz=1&from=webmap&da_par=after_baidu&pcevaname=pc4.1&qt=s&da_src=searchBox.button&wd=%E6%B4%BB%E9%B1%BC%E5%86%9C%E5%AE%B6%E8%8F%9C&c=168&src=0&wd2=&pn=0&sug=0&l=19&b=(12524462.465,4915415;12524952.465,4915809)&from=webmap&biz_forward=%7B%22scaler%22:2,%22styles%22:%22pl%22%7D&sug_forward=&auth=F468SdW9ODYCQDfxcDa7KLFxbaxGBPX3uxHLENxxNHEtBnlQADZZzy1uVt1GgvPUDZYOYIZuVt1cv3uVtGccZcuVtPWv3GuztQZ3wWvUvhgMZSguxzBEHLNRTVtcEWe1GD8zv7u%40ZPuVtcvY1SGpuxztpFNEhjzgjyBKOHQBBODKximNNzCPyGllhIK&device_ratio=2&tn=B_NORMAL_MAP&nn=0&u_loc=12967743,4840033&ie=utf-8&t=1564711758575 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x03ED3190>, 'Connection to 116.209.117.252 timed out. (connect timeout=5)'))
2019-08-02 11:12:59,512  __init__/__init__.py:73  ip不可用：https://116.209.117.252:27390HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x03EF2770>, 'Connection to 116.209.117.252 timed out. (connect timeout=5)'))
2019-08-02 11:13:06,541  __init__/__init__.py:73  json解析错误>>：https://116.209.117.252:27390HTTPSConnectionPool(host='ditu.amap.com', port=443): Max retries exceeded with url: /detail/get/detail?id=B0FFIPJE9Z (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x03EF24D0>, 'Connection to 116.209.117.252 timed out. (connect timeout=5)'))
2019-08-02 11:13:13,557  __init__/__init__.py:73  json解析错误>>：https://116.209.117.252:27390HTTPSConnectionPool(host='ditu.amap.com', port=443): Max retries exceeded with url: /detail/get/detail?id=B0FFF4VIBD (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x03EF2ED0>, 'Connection to 116.209.117.252 timed out. (connect timeout=5)'))
2019-08-02 11:13:20,573  __init__/__init__.py:73  json解析错误>>：https://116.209.117.252:27390HTTPSConnectionPool(host='map.baidu.com', port=443): Max retries exceeded with url: /?newmap=1&reqflag=pcmap&biz=1&from=webmap&da_par=direct&pcevaname=pc4.1&qt=s&da_src=searchBox.button&wd=%E8%B5%B5%E5%9B%9B%E9%A5%B8%E9%A5%B9%E9%9D%A2&c=2589&src=0&wd2=&pn=0&sug=0&l=10&b=(12356672.188326357,4809792.545941422;12556426.244393302,4970411.113472803)&from=webmap&biz_forward=%7B%22scaler%22:2,%22styles%22:%22pl%22%7D&sug_forward=&auth=KFE8H5I%40A9G04PDN00Ef%3D0MMK%40aCHd%3DWuxHLENxzzHxtDpnSCE%40%40By1uVt1GgvPUDZYOYIZuVt1cv3uVtGccZcuVtPWv3GuBtR9KxXwUvhgMZSguxzBEHLNRTVtcEWe1GD8zv7u%40ZPuVteuztexZFTHrwzDvqs2osGIRVOXI33LXFuyWWJL0IBggc1a&device_ratio=2&tn=B_NORMAL_MAP&nn=0&u_loc=12967743,4840033&ie=utf-8&t=1564712258807 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x03EF2970>, 'Connection to 116.209.117.252 timed out. (connect timeout=5)'))
2019-08-02 11:13:27,603  __init__/__init__.py:73  json解析错误>>：https://116.209.117.252:27390HTTPSConnectionPool(host='map.baidu.com', port=443): Max retries exceeded with url: /?newmap=1&reqflag=pcmap&biz=1&from=webmap&da_par=after_baidu&pcevaname=pc4.1&qt=s&da_src=searchBox.button&wd=%E6%B4%BB%E9%B1%BC%E5%86%9C%E5%AE%B6%E8%8F%9C&c=168&src=0&wd2=&pn=0&sug=0&l=19&b=(12524462.465,4915415;12524952.465,4915809)&from=webmap&biz_forward=%7B%22scaler%22:2,%22styles%22:%22pl%22%7D&sug_forward=&auth=F468SdW9ODYCQDfxcDa7KLFxbaxGBPX3uxHLENxxNHEtBnlQADZZzy1uVt1GgvPUDZYOYIZuVt1cv3uVtGccZcuVtPWv3GuztQZ3wWvUvhgMZSguxzBEHLNRTVtcEWe1GD8zv7u%40ZPuVtcvY1SGpuxztpFNEhjzgjyBKOHQBBODKximNNzCPyGllhIK&device_ratio=2&tn=B_NORMAL_MAP&nn=0&u_loc=12967743,4840033&ie=utf-8&t=1564711758575 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x03ED31F0>, 'Connection to 116.209.117.252 timed out. (connect timeout=5)'))
