2019-08-01 10:08:57,520  __init__/__init__.py:73  ip不可用：http://58.22.222.88:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03ED0B30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-01 10:09:03,551  __init__/__init__.py:73  ip不可用：http://58.22.213.107:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0436E030>, 'Connection to 58.22.213.107 timed out. (connect timeout=5)'))
2019-08-01 10:09:09,567  __init__/__init__.py:73  ip不可用：http://117.90.1.198:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0436ED70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-01 10:09:15,583  __init__/__init__.py:73  ip不可用：http://117.90.2.35:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0436EA90>, 'Connection to 117.90.2.35 timed out. (connect timeout=5)'))
2019-08-01 10:09:17,692  __init__/__init__.py:73  ip不可用：http://121.232.148.191:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x03ED0EF0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-01 10:09:23,723  __init__/__init__.py:73  ip不可用：http://175.44.148.100:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x03ED0DF0>, 'Connection to 175.44.148.100 timed out. (connect timeout=5)'))
2019-08-01 10:09:29,739  __init__/__init__.py:73  ip不可用：http://180.118.135.47:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0436EE90>, 'Connection to 180.118.135.47 timed out. (connect timeout=5)'))
2019-08-01 10:09:31,895  __init__/__init__.py:73  ip不可用：http://117.90.1.131:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0436E9F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-01 10:09:38,536  __init__/__init__.py:73  ip不可用：http://14.29.232.142:8082HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-08-01 10:09:40,615  __init__/__init__.py:73  ip不可用：http://36.111.146.161:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0436E270>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-01 10:09:42,724  __init__/__init__.py:73  ip不可用：http://117.90.1.201:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0437F150>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-08-01 10:09:48,740  __init__/__init__.py:73  ip不可用：http://60.188.38.186:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0437F590>, 'Connection to 60.188.38.186 timed out. (connect timeout=5)'))
2019-08-01 10:09:53,850  __init__/__init__.py:73  ip不可用：http://115.28.148.192:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-08-01 10:09:55,974  __init__/__init__.py:73  ip不可用：http://121.232.194.91:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0436E270>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
