2019-07-31 17:59:00,025  __init__/__init__.py:72  _________visit start_________2019-07-31 17:59:00
2019-07-31 17:59:03,274  __init__/__init__.py:72  ip不可用：http://115.218.215.20:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0483DDB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-31 17:59:06,297  __init__/__init__.py:72  ip不可用：http://117.90.252.13:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0485A230>, 'Connection to 117.90.252.13 timed out. (connect timeout=2)'))
2019-07-31 17:59:09,617  __init__/__init__.py:72  ip不可用：http://49.81.125.14:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0485A670>, 'Connection to 49.81.125.14 timed out. (connect timeout=2)'))
2019-07-31 17:59:11,749  __init__/__init__.py:72  ip不可用：http://59.62.35.56:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0485AAB0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-31 17:59:13,906  __init__/__init__.py:72  ip不可用：http://117.90.252.227:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0483DD70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-31 17:59:14,984  __init__/__init__.py:72  ip不可用：http://117.90.137.148:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-31 17:59:18,006  __init__/__init__.py:72  ip不可用：http://120.84.100.29:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0485AB10>, 'Connection to 120.84.100.29 timed out. (connect timeout=2)'))
2019-07-31 17:59:21,027  __init__/__init__.py:72  ip不可用：http://58.253.152.203:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0485A870>, 'Connection to 58.253.152.203 timed out. (connect timeout=2)'))
2019-07-31 17:59:23,184  __init__/__init__.py:72  ip不可用：http://114.235.23.56:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0485A430>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-31 17:59:24,525  __init__/__init__.py:72  ip不可用：http://182.92.113.148:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-07-31 17:59:27,549  __init__/__init__.py:72  ip不可用：http://175.44.154.51:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x05764070>, 'Connection to 175.44.154.51 timed out. (connect timeout=2)'))
2019-07-31 17:59:30,555  __init__/__init__.py:72  ip不可用：http://121.232.148.107:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x05764330>, 'Connection to 121.232.148.107 timed out. (connect timeout=2)'))
2019-07-31 17:59:32,640  __init__/__init__.py:72  ip不可用：http://119.183.249.111:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05764770>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-31 17:59:35,659  __init__/__init__.py:72  ip不可用：http://61.164.39.69:53281HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0485A030>, 'Connection to 61.164.39.69 timed out. (connect timeout=2)'))
2019-07-31 17:59:38,664  __init__/__init__.py:72  ip不可用：http://117.90.6.12:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0485A0D0>, 'Connection to 117.90.6.12 timed out. (connect timeout=2)'))
2019-07-31 17:59:39,666  __init__/__init__.py:72  _________visit end_________2019-07-31 17:59:39

2019-07-31 18:00:00,009  __init__/__init__.py:72  _________visit start_________2019-07-31 18:00:00
2019-07-31 18:00:03,212  __init__/__init__.py:72  ip不可用：http://115.218.215.20:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0483D050>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-31 18:00:06,219  __init__/__init__.py:72  ip不可用：http://117.90.252.13:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x04833FB0>, 'Connection to 117.90.252.13 timed out. (connect timeout=2)'))
2019-07-31 18:00:09,237  __init__/__init__.py:72  ip不可用：http://49.81.125.14:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x057648D0>, 'Connection to 49.81.125.14 timed out. (connect timeout=2)'))
2019-07-31 18:00:11,394  __init__/__init__.py:72  ip不可用：http://59.62.35.56:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05764070>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-31 18:00:13,529  __init__/__init__.py:72  ip不可用：http://117.90.252.227:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05764C70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-31 18:00:14,600  __init__/__init__.py:72  ip不可用：http://117.90.137.148:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-31 18:00:17,620  __init__/__init__.py:72  ip不可用：http://120.84.100.29:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0483D470>, 'Connection to 120.84.100.29 timed out. (connect timeout=2)'))
2019-07-31 18:00:20,636  __init__/__init__.py:72  ip不可用：http://58.253.152.203:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x04833FF0>, 'Connection to 58.253.152.203 timed out. (connect timeout=2)'))
2019-07-31 18:00:22,793  __init__/__init__.py:72  ip不可用：http://114.235.23.56:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0485A4F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-31 18:00:24,076  __init__/__init__.py:72  ip不可用：http://182.92.113.148:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-07-31 18:00:27,093  __init__/__init__.py:72  ip不可用：http://175.44.154.51:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x05764490>, 'Connection to 175.44.154.51 timed out. (connect timeout=2)'))
2019-07-31 18:00:30,096  __init__/__init__.py:72  ip不可用：http://121.232.148.107:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x05764350>, 'Connection to 121.232.148.107 timed out. (connect timeout=2)'))
2019-07-31 18:00:32,197  __init__/__init__.py:72  ip不可用：http://119.183.249.111:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x057649B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-31 18:00:35,215  __init__/__init__.py:72  ip不可用：http://61.164.39.69:53281HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x05772070>, 'Connection to 61.164.39.69 timed out. (connect timeout=2)'))
2019-07-31 18:00:38,217  __init__/__init__.py:72  ip不可用：http://117.90.6.12:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0485A270>, 'Connection to 117.90.6.12 timed out. (connect timeout=2)'))
2019-07-31 18:00:39,220  __init__/__init__.py:72  _________visit end_________2019-07-31 18:00:39

2019-07-31 18:01:00,010  __init__/__init__.py:72  _________visit start_________2019-07-31 18:01:00
2019-07-31 18:01:03,269  __init__/__init__.py:72  ip不可用：http://115.218.215.20:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x057647F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-31 18:01:05,415  __init__/__init__.py:72  ip不可用：http://117.90.252.13:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05764330>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-31 18:01:08,423  __init__/__init__.py:72  ip不可用：http://49.81.125.14:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x057643D0>, 'Connection to 49.81.125.14 timed out. (connect timeout=2)'))
2019-07-31 18:01:10,563  __init__/__init__.py:72  ip不可用：http://59.62.35.56:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0485AE70>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-31 18:01:12,696  __init__/__init__.py:72  ip不可用：http://117.90.252.227:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05772310>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-31 18:01:13,782  __init__/__init__.py:72  ip不可用：http://117.90.137.148:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))
2019-07-31 18:01:16,803  __init__/__init__.py:72  ip不可用：http://120.84.100.29:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0485AB30>, 'Connection to 120.84.100.29 timed out. (connect timeout=2)'))
2019-07-31 18:01:19,817  __init__/__init__.py:72  ip不可用：http://58.253.152.203:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0485A910>, 'Connection to 58.253.152.203 timed out. (connect timeout=2)'))
2019-07-31 18:01:21,940  __init__/__init__.py:72  ip不可用：http://114.235.23.56:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05764AD0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-31 18:01:23,419  __init__/__init__.py:72  ip不可用：http://182.92.113.148:8118HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', OSError('Tunnel connection failed: 503 Too many open connections')))
2019-07-31 18:01:26,446  __init__/__init__.py:72  ip不可用：http://175.44.154.51:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x05764B50>, 'Connection to 175.44.154.51 timed out. (connect timeout=2)'))
2019-07-31 18:01:29,452  __init__/__init__.py:72  ip不可用：http://121.232.148.107:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x05764690>, 'Connection to 121.232.148.107 timed out. (connect timeout=2)'))
2019-07-31 18:01:31,526  __init__/__init__.py:72  ip不可用：http://119.183.249.111:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x05764AF0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-31 18:01:34,547  __init__/__init__.py:72  ip不可用：http://61.164.39.69:53281HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x05761070>, 'Connection to 61.164.39.69 timed out. (connect timeout=2)'))
2019-07-31 18:01:37,553  __init__/__init__.py:72  ip不可用：http://117.90.6.12:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x057645F0>, 'Connection to 117.90.6.12 timed out. (connect timeout=2)'))
2019-07-31 18:01:38,566  __init__/__init__.py:72  _________visit end_________2019-07-31 18:01:38

2019-07-31 18:02:00,005  __init__/__init__.py:72  _________visit start_________2019-07-31 18:02:00
2019-07-31 18:02:03,225  __init__/__init__.py:72  ip不可用：http://115.218.215.20:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0483DF90>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-31 18:02:06,245  __init__/__init__.py:72  ip不可用：http://117.90.252.13:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0485A290>, 'Connection to 117.90.252.13 timed out. (connect timeout=2)'))
2019-07-31 18:02:09,246  __init__/__init__.py:72  ip不可用：http://49.81.125.14:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0485AA90>, 'Connection to 49.81.125.14 timed out. (connect timeout=2)'))
2019-07-31 18:02:11,417  __init__/__init__.py:72  ip不可用：http://59.62.35.56:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x057613B0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-31 18:02:13,601  __init__/__init__.py:72  ip不可用：http://117.90.252.227:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x057617F0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。')))
2019-07-31 18:02:14,765  __init__/__init__.py:72  ip不可用：http://117.90.137.148:9000HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ProxyError('Cannot connect to proxy.', ConnectionAbortedError(10053, '你的主机中的软件中止了一个已建立的连接。', None, 10053, None)))
2019-07-31 18:02:17,782  __init__/__init__.py:72  ip不可用：http://120.84.100.29:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0485A630>, 'Connection to 120.84.100.29 timed out. (connect timeout=2)'))
2019-07-31 18:02:20,787  __init__/__init__.py:72  ip不可用：http://58.253.152.203:9999HTTPSConnectionPool(host='blog.csdn.net', port=443): Max retries exceeded with url: /a_yue10/article/details/97392747 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x0483DF50>, 'Connection to 58.253.152.203 timed out. (connect timeout=2)'))
